# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20170102_2103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['sort']},
        ),
        migrations.AddField(
            model_name='place',
            name='sort',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
