# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_auto_20170102_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='plan_at',
            new_name='plan_date',
        ),
        migrations.AddField(
            model_name='place',
            name='plan_time',
            field=models.CharField(blank=True, choices=[('allday', 'All day'), ('midnight', 'Midnight'), ('dawn', 'Dawn'), ('morning', 'Morning'), ('noon', ' Noon'), ('afternoon', 'Afternoon'), ('dust', 'DUST'), ('evening', 'Evening')], max_length=9, null=True),
        ),
    ]
