# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='plan_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
