# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_auto_20170112_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelConstraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=9)),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='name_en',
            field=models.CharField(blank=True, max_length=196, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='search',
            field=models.CharField(blank=True, max_length=196, null=True),
        ),
    ]
