# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_auto_20170205_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='transit_no',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='travel_type',
            field=models.CharField(blank=True, choices=[('driving', 'Driving'), ('walking', 'Walking'), ('transit', 'Transit'), ('flight', 'Flight')], max_length=7, null=True),
        ),
    ]
