# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_place_transit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='transit_ticket_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
