# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_place_transit_arrive_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelconstraint',
            name='type',
            field=models.CharField(max_length=16),
        ),
    ]
