# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_travelconstraint_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelconstraint',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
