# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_travelconstraint_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelconstraint',
            name='type',
            field=models.CharField(choices=[('departure-before', 'Must departure before'), ('departure-after', 'Must departure after'), ('arrive-before', 'Must arrive before'), ('arrive-after', 'Must arrive after')], max_length=16),
        ),
    ]
