# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0015_auto_20170205_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('decided', 'Decided'), ('yet-decided', 'Yet decided')], max_length=11)),
                ('ticket_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='place',
            name='transit_arrive_time',
        ),
        migrations.RemoveField(
            model_name='place',
            name='transit_no',
        ),
        migrations.RemoveField(
            model_name='place',
            name='transit_ticket_price',
        ),
        migrations.RemoveField(
            model_name='place',
            name='transit_time',
        ),
        migrations.RemoveField(
            model_name='place',
            name='travel_type',
        ),
        migrations.AddField(
            model_name='transit',
            name='a',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='from+', to='travel.Place'),
        ),
        migrations.AddField(
            model_name='transit',
            name='b',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='to+', to='travel.Place'),
        ),
    ]
