# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0016_auto_20170205_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=196)),
                ('type', models.CharField(choices=[('been', 'Been'), ('plan', 'Plan'), ('home', 'Home')], max_length=4)),
                ('latitude', models.DecimalField(decimal_places=14, max_digits=17)),
                ('longitude', models.DecimalField(decimal_places=14, max_digits=17)),
            ],
        ),
    ]
