# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroundFloorTimber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=192)),
                ('image', models.ImageField(upload_to=b'')),
                ('added_at', models.DateTimeField()),
            ],
        ),
    ]
