# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groundfloortimber',
            name='image',
            field=models.ImageField(upload_to='ground-floor-timber'),
        ),
    ]
