# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 01:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_auto_20161229_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=92)),
                ('show_in_nav', models.BooleanField()),
                ('link_text', models.CharField(max_length=19)),
                ('content', tinymce.models.HTMLField()),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
