# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20161230_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='link',
            field=models.CharField(default=None, max_length=192),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(max_length=192),
        ),
    ]
