# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20161230_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content_width',
            field=models.CharField(choices=[('2', '2'), ('4', '4'), ('6', '6'), ('8', '8'), ('10', '10'), ('12', '12')], default=12, max_length=2),
        ),
    ]
