# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 08:14
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_page_content_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=192)),
                ('link', models.CharField(max_length=192)),
                ('desc', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
