# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 08:21
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_page_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
