# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20161230_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=192)),
                ('link_text', models.CharField(max_length=192)),
                ('target', models.CharField(choices=[('_blank', 'New window/tab'), ('_self', 'Current window')], default='_self', max_length=7)),
                ('type', models.CharField(choices=[('i', 'Internal'), ('e', 'External')], default='e', max_length=1)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_category', to='home.Category')),
            ],
        ),
        migrations.RemoveField(
            model_name='page',
            name='link_text',
        ),
        migrations.RemoveField(
            model_name='page',
            name='show_in_nav',
        ),
        migrations.AddField(
            model_name='link',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_category', to='home.Page'),
        ),
    ]
