# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20161230_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.CharField(choices=[('p', 'Page'), ('c', 'Category'), ('e', 'External')], default='c', max_length=1),
        ),
    ]
