# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20161230_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='page-cover'),
        ),
    ]
