# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-27 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_pagesection_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='content_offset',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], default=0, max_length=2),
        ),
    ]
